### ISSUE TITLE
Ignore mouse wheel inputs when Alt or Shift are currently pressed

### ISSUE THREAD

**Issue by pakhrom** [BobbyShmurner/Zoom#1]
Ignore mouse wheel inputs when Alt is currently pressed to not interfere with HJfod's Quick Volume Controls mod when changing the game's volume levels while the game is paused.

**Comment by BobbyShmurner** [comment]
Oh yeah, I'll get on that right now :D

**Comment by BobbyShmurner** [comment]
Ok, I've updated the mod and it's been submitted for review

If you'd like to install it before it's officially released to the mod index, you can download it from the [Releases](https://github.com/BobbyShmurner/Zoom/releases/tag/v1.1.0) tab and place it in the "geode/mods" folder located in your game's install directory
